# Generated by Django 6.0.1 on 2026-01-29 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('INSUMO', 'Insumo'), ('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], default='INSUMO', max_length=20)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('controlar_stock', models.BooleanField(default=True)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CabeceraTransaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_operacion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_razon_social', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('es_cliente', models.BooleanField(default=False)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galpon',
            fields=[
                ('id_galpon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.articulo')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Gestion.cabeceratransaccion')),
            ],
        ),
        migrations.AddField(
            model_name='cabeceratransaccion',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.entidad'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('aves_iniciales', models.IntegerField()),
                ('aves_actuales', models.IntegerField(editable=False)),
                ('estado', models.BooleanField(default=True)),
                ('galpon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.galpon')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInterno',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('CONSUMO', 'Consumo'), ('PRODUCCION', 'Produccion')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.articulo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.lote')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBajas',
            fields=[
                ('id_baja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(choices=[('MUERTE_NATURAL', 'Muerte Natural'), ('ACCIDENTE', 'Accidente'), ('DESCARTE', 'Descarte'), ('DEPREDADOR', 'Depredador')], default='MUERTE_NATURAL', max_length=20)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.lote')),
            ],
        ),
    ]
