# Generated by Django 6.0.1 on 2026-01-29 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_proxima_vacuna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroVacunacion',
            fields=[
                ('id_vacunacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proxima_fecha_sugerida', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.lote')),
            ],
        ),
    ]
