# Generated by Django 6.0.1 on 2026-02-03 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_lote_fecha_proxima_vacuna_registrovacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='es_insumo_receta',
            field=models.BooleanField(default=False, help_text='Marcar si es un envase o insumo auxiliar para recetas (no se muestra en Kiosco)'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(help_text='Cantidad de ingrediente por unidad de producto')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_en_recetas', to='Gestion.articulo')),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'PRODUCTO'}, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_receta', to='Gestion.articulo')),
            ],
            options={
                'unique_together': {('producto', 'ingrediente')},
            },
        ),
    ]
