# Generated by Django 6.0.1 on 2026-02-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_articulo_es_insumo_receta_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('PRODUCCION', 'Producción'), ('CONSUMO', 'Consumo'), ('AJUSTE', 'Ajuste Manual'), ('EDICION', 'Edición Metadata')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, help_text='Magnitude of change', max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Gestion.articulo')),
            ],
        ),
    ]
