# Generated by Django 6.0.1 on 2026-02-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_logarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio_referencia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio base para compras o ventas', max_digits=10),
        ),
    ]
