# Generated by Django 6.0.1 on 2026-02-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_articulo_precio_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(choices=[('INSUMO', 'Insumo'), ('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='unidad_medida',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Kg', 'Kg'), ('Litro', 'Litro')], default='Unidad', max_length=50),
        ),
    ]
