# Generated by Django 6.0.1 on 2026-02-03 04:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_alter_articulo_tipo_alter_articulo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientointerno',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
