# Generated by Django 6.0.1 on 2026-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_movimientointerno_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabeceratransaccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
