# Generated by Django 6.0.1 on 2026-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_cabeceratransaccion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceratransaccion',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=20),
        ),
    ]
